name: Bug Report
description: Report a reproducible bug or regression.
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Code
      value: |
        ```js
        // code goes here
        ```
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Live example
      value: |
        Link to jsfiddle (https://jsfiddle.net/) or codesandbox (https://codesandbox.io/) demonstrating the bug.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem (drag and drop the image).
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Library Version
      description: What version of the library are you using?
      placeholder: v
    validations:
      required: true
  - type: input
    id: three_version
    attributes:
      label: Three.js Version
      description: What version of three.js are you using?
      placeholder: r
    validations:
      required: true
